# Generated by Django 5.2.7 on 2025-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(default='no username', max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('certificate', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, choices=[('presenter', 'Presenter'), ('debater', 'Debater'), ('observer', 'Observer')], default='observer', max_length=10, null=True)),
            ],
        ),
    ]
